# Generated by Django 4.2.4 on 2023-08-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Software",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=256, verbose_name="Title"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                ("count", models.PositiveSmallIntegerField(verbose_name="Count")),
            ],
            options={
                "verbose_name": "Software",
                "verbose_name_plural": "Software",
                "ordering": ("-price",),
            },
        ),
    ]
