# Generated by Django 4.2.4 on 2023-08-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("software", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="software",
            name="currency",
            field=models.CharField(
                default=None, max_length=30, verbose_name="Currency"
            ),
            preserve_default=False,
        ),
    ]
