# Generated by Django 4.2.4 on 2023-08-07 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("software", "0002_software_currency"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="software",
            options={
                "ordering": ("price",),
                "verbose_name": "Software",
                "verbose_name_plural": "Software",
            },
        ),
    ]
